branches:
  only:
  - master

shallow_clone: true

image: Visual Studio 2017
version: 1.0.{build}
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true

before_build:
  - dotnet restore

test:
  assemblies:
    only:
      - RtMidi.Core.Tests.dll

deploy:
  provider: NuGet
  api_key:
    secure: vBlSrCQ4s/mllI3OlT4VDnQapsDxgaJoLvZ7jn+9R1oPId9QUH8t1QSkUN+zIH5K
  skip_symbols: true
  artifact: /.*\.nupkg/